version: '3'
services:
  bitcoind:
    image: lncm/bitcoind:v26.0
    container_name: bitcoind
    restart: on-failure
    stop_grace_period: 30s
    user: 0:0
    healthcheck:
      test: [ "CMD", "bitcoin-cli", "getnetworkinfo" ]
      interval: 2s
    volumes:
      - ./infrastructure/dev/configs/bitcoind.conf:/root/.bitcoin/bitcoin.conf
      - ./volumes.dev/bitcoind:/root/.bitcoin
      - ./infrastructure/dev/configs/faucet.sh:/faucet.sh
    command: [ "-addnode=bitcoind2:18444" ]
    entrypoint:
      - "sh"
      - "-c"
      - "bitcoind"
    ports:
      - 18443:18443
      - 18444:18444

  bitcoind2:
    image: lncm/bitcoind:v26.0
    container_name: bitcoind2
    restart: on-failure
    stop_grace_period: 30s
    user: 0:0
    healthcheck:
      test: [ "CMD", "bitcoin-cli", "getnetworkinfo" ]
      interval: 2s
    volumes:
      - ./infrastructure/dev/configs/bitcoind.conf:/root/.bitcoin/bitcoin.conf
      - ./volumes.dev/bitcoind2:/root/.bitcoin
    command: [ "-addnode=bitcoind:18444" ]
    profiles:
      - end_to_end
    ports:
      - 18445:18443
      - 18446:18444

  electrs:
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoind:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      bitcoind:
        condition: service_healthy
    ports:
      - 30000:30000
    volumes:
      - ./volumes.dev/bitcoind/:/config
    profiles:
      - end_to_end
    restart: on-failure

  electrs2:
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs2
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoind2:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      bitcoind2:
        condition: service_healthy
    ports:
      - 30001:30000
    volumes:
      - ./volumes.dev/bitcoind2/:/config
    profiles:
      - end_to_end
    restart: on-failure

  yuvd:
    image: akitamiabtc/yuvd
    build:
      context: .
      dockerfile: ./infrastructure/build/yuvd.dockerfile
    container_name: yuvd
    restart: on-failure
    volumes:
      - ./infrastructure/dev/configs/yuvd.toml:/config.toml
      - ./volumes.dev/yuvd:/var/yuvd
    ports:
      - 8001:8001 # p2p
      - 18333:18333 # rpc
    depends_on:
      bitcoind:
        condition: service_healthy

  yuvd2:
    image: akitamiabtc/yuvd
    build:
      context: .
      dockerfile: ./infrastructure/build/yuvd.dockerfile
    restart: on-failure
    profiles:
      - two_nodes_setup
      - three_nodes_setup
      - end_to_end
    container_name: yuvd2
    volumes:
      - ./infrastructure/dev/configs/yuvd-2.toml:/config.toml
      - ./volumes.dev/yuvd2:/var/yuvd2
    ports:
      - 8003:8003 # p2p
      - 18335:18335 # rpc
    depends_on:
      bitcoind:
        condition: service_healthy
      yuvd:
        condition: service_started

  yuvd3:
    image: akitamiabtc/yuvd
    build:
      context: .
      dockerfile: ./infrastructure/build/yuvd.dockerfile
    depends_on:
      bitcoind:
        condition: service_healthy
      yuvd:
        condition: service_started
      yuvd2:
        condition: service_started
    restart: on-failure
    profiles:
      - three_nodes_setup
      - end_to_end
    container_name: yuvd3
    volumes:
      - ./infrastructure/dev/configs/yuvd-3.toml:/config.toml
      - ./volumes.dev/yuvd3:/var/yuvd3
    ports:
      - 8004:8004 # p2p
      - 18336:18336 # rpc

volumes:
  bitcoind:
  yuvd:
  yuvd2:
  yuvd3:
