name: "Rust setup"

description: Installs Rust stable toolchain

runs:
  using: composite
  steps:
    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: "rustfmt, clippy"
        toolchain: 1.74.0