name: Check, test, lint CI

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: "-Dwarnings"

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust Setup
        uses: ./.github/actions/rust-setup 

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Run cargo check
        run: cargo check

      - name: Run cargo check on release version
        run: cargo check --release

      - name: Run Clippy
        run: cargo clippy --all-targets

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust Setup
        uses: ./.github/actions/rust-setup 

      - name: Run cargo build
        run: cargo build --no-default-features

      - name: Run cargo build with bulletproofs
        run: cargo build --no-default-features --features bulletproof

  tests:
    needs: [ build, lints ]
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust setup
        uses: ./.github/actions/rust-setup

      - name: Run cargo unittests
        run: cargo test --lib

      - name: Run cargo doctests
        run: cargo test --doc

      - name: Run no-std tests
        run: |
          cargo test -p yuv-pixels --no-default-features --features no-std,consensus && \
          cargo test -p yuv-types --no-default-features --features no-std,consensus

  doctests:
    needs: [ build, lints ]
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust setup
        uses: ./.github/actions/rust-setup

      - name: Run cargo doc
        run: cargo doc --no-deps --all --exclude bdk --exclude bitcoincore-rpc --exclude jsonrpc